# Generated by Django 3.1.6 on 2021-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('uid', 'bid'), name='uid_and_bid_uniq'),
        ),
    ]
